name: weather_app
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # CORE
  dart_kit:
    path: packages/dart_kit

  rx_viewmodels:
    path: packages/rx_viewmodels

  # DI
  get_it: ^7.6.7
  injectable: ^2.4.0

  # NATIVE HELPERS
  path_provider: ^2.1.2
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: 9.0.0


  # NETWORKING
  dio: ^5.4.1
  dio_smart_retry: 6.0.0
  pretty_dio_logger: 1.3.1
  connectivity_plus: ^5.0.2

  # DATA
  get: 4.6.6
  rxdart: 0.27.7
  stock: 1.1.0
  hive: 2.2.3
  uuid: ^4.3.3
  equatable: 2.0.5
  collection: ^1.18.0
  intl: ^0.19.0
  freezed_annotation: 2.4.1
  geolocator: 11.0.0

  # UI
  auto_route: ^7.9.0
  flutter_screenutil: 5.9.0
  flutter_svg: ^2.0.10+1
  cupertino_icons: 1.0.6
  flutter_spinkit: 5.2.0
  timeago: ^3.6.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  build_runner: ^2.4.8
  intl_utils: ^2.8.7
  http_mock_adapter: ^0.6.1
  faker_dart: 0.2.1

  # generator libs
  injectable_generator: ^2.6.1
  auto_route_generator: 7.3.2
  flutter_launcher_icons: 0.13.1
  flutter_gen_runner: ^5.4.0
  mockito: ^5.4.4
  json_serializable: 6.7.1


flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

# creates a binding between your translations from .arb files and your Flutter app.
# It generates boilerplate code for official Dart Intl library and adds auto-complete for keys in Dart code.
# Run command: flutter pub run intl_utils:generate
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: lib/l10n
  output_dir: lib/base/utils/localizations_generated
  template-arb-file: intl_en.arb