include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    constant_identifier_names: false
    depend_on_referenced_packages: false

analyzer:
  exclude:
    - 'example/main.dart'
  errors:
    invalid_annotation_target: ignore
    # depend_on_referenced_packages: error

