name: dart_kit
description: Core Dart Kit Utils
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  logger: 2.0.2+1
  meta: 1.9.1
  rxdart: 0.27.7

dev_dependencies:
  build_runner: 2.4.6
  lint: 2.1.2
  mockito: 5.4.2
  test: 1.24.9
