name: dart_kit
description: Core Dart Kit Utils
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  logger: ^2.1.0
  meta: ^1.11.0
  rxdart: 0.27.7

dev_dependencies:
  build_runner: ^2.4.8
  lint: ^2.3.0
  mockito: ^5.4.4
  test: ^1.25.2
